[2025-02-11T17:05:32.632+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-11T17:05:32.697+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_INETUM_ETL.extract_data manual__2025-02-11T17:05:25.149343+00:00 [queued]>
[2025-02-11T17:05:32.736+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_INETUM_ETL.extract_data manual__2025-02-11T17:05:25.149343+00:00 [queued]>
[2025-02-11T17:05:32.737+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-02-11T17:05:32.789+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_data> on 2025-02-11 17:05:25.149343+00:00
[2025-02-11T17:05:32.818+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2709) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T17:05:32.826+0000] {standard_task_runner.py:63} INFO - Started process 2722 to run task
[2025-02-11T17:05:32.827+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_INETUM_ETL', 'extract_data', 'manual__2025-02-11T17:05:25.149343+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpz31m10vr']
[2025-02-11T17:05:32.830+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask extract_data
[2025-02-11T17:05:32.989+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_INETUM_ETL.extract_data manual__2025-02-11T17:05:25.149343+00:00 [running]> on host 9a237c96c334
[2025-02-11T17:05:33.250+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andres Urrea' AIRFLOW_CTX_DAG_ID='DAG_INETUM_ETL' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T17:05:25.149343+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T17:05:25.149343+00:00'
[2025-02-11T17:05:33.255+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-11T17:05:40.356+0000] {dag_etl.py:46} INFO - Proceso de extraccion de data realizado con exito
[2025-02-11T17:05:40.360+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-02-11T17:05:40.361+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-11T17:05:40.383+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=DAG_INETUM_ETL, task_id=extract_data, execution_date=20250211T170525, start_date=20250211T170532, end_date=20250211T170540
[2025-02-11T17:05:40.442+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-11T17:05:40.512+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-11T17:05:40.516+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
